services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    environment:
      - FLASK_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
