apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: k8s-assignment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: yashhuu/k8s-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000